# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode11.4
language: swift
xcode_workspace: Demirciy.xcworkspace
xcode_destination: platform=iOS Simulator,name=iPhone 11
podfile: Podfile

before_install:
- brew update
- pod install

# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/AuthTextField.xcworkspace -scheme AuthTextField-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
